package com.example.urlshortener.dto;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_URL,
    URL_NOT_FOUND,
    URL_DISABLED,
    URL_EXPIRED,
    URL_DELETED,
    ALIAS_CONFLICT,
    IDEMPOTENCY_CONFLICT,
    OPTIMISTIC_LOCK_CONFLICT,
    PRECONDITION_REQUIRED,
    RATE_LIMIT_EXCEEDED,
    INVALID_DATE_RANGE,
    INTERNAL_ERROR,
    SERVICE_UNAVAILABLE
}
