package com.example.urlshortener.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.example.urlshortener.entity.ClickEvent;
import com.example.urlshortener.entity.CodeType;
import com.example.urlshortener.entity.ShortenedUrl;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

@JdbcTest
@ActiveProfiles("test")
class AnalyticsQueryRepositoryTest {
    @Autowired
    private JdbcTemplate jdbcTemplate;

    private AnalyticsQueryRepository analyticsQueryRepository;

    @BeforeEach
    void setUp() {
        analyticsQueryRepository = new AnalyticsQueryRepository(jdbcTemplate);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS shortened_url (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    public_id VARCHAR(36) NOT NULL,
                    short_code VARCHAR(48) NOT NULL,
                    original_url VARCHAR(2048) NOT NULL,
                    code_type VARCHAR(16) NOT NULL,
                    status VARCHAR(16) NOT NULL,
                    expires_at TIMESTAMP NULL,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL,
                    deleted_at TIMESTAMP NULL,
                    version BIGINT NOT NULL DEFAULT 0
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS click_event (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    shortened_url_id BIGINT NOT NULL,
                    occurred_at TIMESTAMP NOT NULL,
                    referrer_host VARCHAR(255),
                    browser_family VARCHAR(100),
                    operating_system_family VARCHAR(100),
                    device_type VARCHAR(50),
                    correlation_id VARCHAR(100)
                )
                """);
    }

    @Test
    void returnsSummary() {
        long shortenedUrlId = insertUrl();
        insertClick(shortenedUrlId, "2026-08-07T10:00:00Z", "google.com", "CHROME", "WINDOWS", "DESKTOP");
        insertClick(shortenedUrlId, "2026-08-07T11:00:00Z", "github.com", "CHROME", "WINDOWS", "DESKTOP");

        Timestamp from = Timestamp.from(Instant.parse("2026-08-07T00:00:00Z"));
        Timestamp to = Timestamp.from(Instant.parse("2026-08-08T00:00:00Z"));

        AnalyticsQueryRepository.SummaryRow summary = analyticsQueryRepository.getSummary(shortenedUrlId, from, to);

        assertEquals(2, summary.clicks());
        assertEquals(Instant.parse("2026-08-07T11:00:00Z"), summary.lastEventAt());
    }

    @Test
    void returnsReferrerCounts() {
        long shortenedUrlId = insertUrl();
        insertClick(shortenedUrlId, "2026-08-07T10:00:00Z", "google.com", "CHROME", "WINDOWS", "DESKTOP");
        insertClick(shortenedUrlId, "2026-08-07T11:00:00Z", "google.com", "CHROME", "WINDOWS", "DESKTOP");
        insertClick(shortenedUrlId, "2026-08-07T12:00:00Z", "github.com", "FIREFOX", "LINUX", "DESKTOP");

        Timestamp from = Timestamp.from(Instant.parse("2026-08-07T00:00:00Z"));
        Timestamp to = Timestamp.from(Instant.parse("2026-08-08T00:00:00Z"));

        List<AnalyticsQueryRepository.NamedCountRow> results = analyticsQueryRepository.getReferrers(shortenedUrlId, from, to, 10);

        assertEquals(2, results.size());
        assertEquals("google.com", results.getFirst().name());
        assertEquals(2, results.getFirst().clicks());
    }

    @Test
    void returnsDeviceCounts() {
        long shortenedUrlId = insertUrl();
        insertClick(shortenedUrlId, "2026-08-07T10:00:00Z", null, "CHROME", "WINDOWS", "DESKTOP");
        insertClick(shortenedUrlId, "2026-08-07T11:00:00Z", null, "SAFARI", "IOS", "MOBILE");
        insertClick(shortenedUrlId, "2026-08-07T12:00:00Z", null, "SAFARI", "IOS", "MOBILE");

        Timestamp from = Timestamp.from(Instant.parse("2026-08-07T00:00:00Z"));
        Timestamp to = Timestamp.from(Instant.parse("2026-08-08T00:00:00Z"));

        List<AnalyticsQueryRepository.NamedCountRow> results = analyticsQueryRepository.getDeviceTypes(shortenedUrlId, from, to);

        assertEquals(2, results.size());
        assertEquals("MOBILE", results.getFirst().name());
        assertEquals(2, results.getFirst().clicks());
    }

    private long insertUrl() {
        jdbcTemplate.update("""
                INSERT INTO shortened_url (
                    public_id,
                    short_code,
                    original_url,
                    code_type,
                    status,
                    created_at,
                    updated_at,
                    version
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                UUID.randomUUID().toString(),
                "abc12345",
                "https://example.com",
                CodeType.GENERATED.name(),
                "ACTIVE",
                Timestamp.from(Instant.parse("2026-08-01T12:00:00Z")),
                Timestamp.from(Instant.parse("2026-08-01T12:00:00Z")),
                0);

        return jdbcTemplate.queryForObject("SELECT MAX(id) FROM shortened_url", Long.class);
    }

    private void insertClick(long shortenedUrlId, String occurredAt, String referrer, String browser, String operatingSystem, String deviceType) {
        jdbcTemplate.update("""
                INSERT INTO click_event (
                    shortened_url_id,
                    occurred_at,
                    referrer_host,
                    browser_family,
                    operating_system_family,
                    device_type,
                    correlation_id
                )
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                shortenedUrlId,
                Timestamp.from(Instant.parse(occurredAt)),
                referrer,
                browser,
                operatingSystem,
                deviceType,
                "correlation-123");
    }
}